#!/usr/bin/env /opt/saltstack/salt/bin/python3
import glob
import os
from typing import List, Tuple
import boto3, botocore
import socket
from more_itertools import partition
from dataclasses import dataclass

ROOT_DIR = '/var/log/bondlink'
BUCKET = 'bondlink-data-east'
HOSTNAME = socket.gethostname()
ENV = "prod" if "prod" in HOSTNAME else "staging"
DEBUG = False

@dataclass
class LogKey:
  log: str
  key: str

def is_crap_log(x: str) -> bool:
  return 'apache-aws.log' in x

# Get all of our log files, ignoring, for now, a single pattern of the apache-aws
# log that is generated by underlying Java libraries
def base_logs() -> Tuple[List[str],List[str]]:
  return list(map(list, partition(is_crap_log, glob.glob("*.gz", root_dir=ROOT_DIR))))

# eah LogKey should represent a LogKey.key that does not exist, but not required.
def perform_backups(copy_logs:List[LogKey], s3: boto3.client):
  for log in copy_logs:
    try:
      print(f"Copying {log.log} to {log.key}")
      with open(f'{ROOT_DIR}/{log.log}', 'rb') as fb:
        s3.put_object(Bucket=BUCKET, Body=fb, Key=log.key)
    except Exception as e:
      print(f"Failed to copy {BUCKET}, Bytes={ROOT_DIR}/{log.log}, Key={log.key}, Exception: {e}")

# Collect logs that are on the file system, but missing from s3
def backup_logs(s3:boto3.client, logs: List[str]) -> List[LogKey]:
  copy_logs = []
  if len(logs):
    print(f"Log Files to Check {len(logs)}")

  for log in logs:
    #typical format bondlink-debug.log.2023-10-21.gz
    fldr = '-'.join(log.split('.')[-2].split('-')[0:2])
    key = f'weblogs/{ENV}/{HOSTNAME}/{fldr}/{log}'
    if DEBUG:
      print(f'{BUCKET}/{key}')

    #if the key doesn't exist we add it to be copied
    try:
      s3.head_object(Bucket=BUCKET,Key=key)
    except botocore.exceptions.ClientError as ce:
      if "404" in str(ce):
        copy_logs.append(LogKey(log, key))
      else:
        print(f"Non 404 Exception Bucket: {BUCKET} Key: {key}")

  print(f"Log files to update {len(copy_logs)}")

  return copy_logs

# This is mostly for aws-apache.log to stop sucking up space
def cleanup(logs):
  for f in logs:
    print(f"Removing {ROOT_DIR}/{f}")
    try:
      os.unlink(f'{ROOT_DIR}/{f}')
    except Exception as e:
      print(f"Failed to remove {ROOT_DIR}/{f}, Exception: {e}")

if __name__ == '__main__':
  s3 = boto3.client('s3')
  bondlink_logs, crap_logs = base_logs()
  if len(bondlink_logs):
    perform_backups(backup_logs(s3, bondlink_logs), s3)
  else:
    print("No logs to update")

  cleanup(crap_logs)
