id: saltrun-certificate-renewal
namespace: bondlink-jobs.deploy

description: |
  Restart all application servers.

tasks:
  - id: restart_app_servers
    type: io.kestra.plugin.fs.ssh.Command
    host: prodjump01.bondlink.vpc
    port: "2007"
    username: bldeploy
    authMethod: PUBLIC_KEY
    privateKey: "{{ secret('SSH_PRIVATE_KEY') }}"
    strictHostKeyChecking: "no"
    commands:
      - |
        java -jar /var/bondlink/bondlink-deploy.jar restart-current -e prod

  - id: notify_success
    type: io.kestra.plugin.notifications.sendgrid.SendGridMailSend
    sendgridApiKey: "{{ secret('SENDGRID_API_KEY') }}"
    from: kestra@bondlink.com
    to:
      - jeff@bondlink.com
    subject: "Kestra[prod_cron] Certification Renewal Success"
    htmlContent: "Execution {{ execution.id }} of {{ flow.namespace }}.{{ flow.id }} succeeded."

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 7 * * 1"
    timezone: UTC

errors:
  - id: notify_failure
    type: io.kestra.plugin.notifications.sendgrid.SendGridMailSend
    sendgridApiKey: "{{ secret('SENDGRID_API_KEY') }}"
    from: kestra@bondlink.com
    to:
      - jeff@bondlink.com
    subject: "Kestra[prod_cron] Certification Renewal Failed"
    htmlContent: |
      Execution {{ execution.id }} of {{ flow.namespace }}.{{ flow.id }} failed.
      Failed task: {{ tasksWithState('FAILED')[0].id }}
